#!/bin/env bash

lang_src_path=./resources/lang/src/
lang_path=./resources/lang/

for i in $lang_src_path*.ts
do
    source_filename=$(basename -- $i)

    filename="${source_filename%.*}"

    lrelease "$i" -qm "$lang_path$filename.qm"
done
