# Form implementation generated from reading ui file 'layouts/WidgetMovie.ui'
#
# Created by: PyQt6 UI code generator 6.4.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_WidgetMovie(object):
    def setupUi(self, WidgetMovie):
        WidgetMovie.setObjectName("WidgetMovie")
        WidgetMovie.resize(754, 47)
        self.LayoutWidget = QtWidgets.QVBoxLayout(WidgetMovie)
        self.LayoutWidget.setContentsMargins(0, 0, 0, 0)
        self.LayoutWidget.setObjectName("LayoutWidget")
        self.Container = QtWidgets.QFrame(WidgetMovie)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Container.sizePolicy().hasHeightForWidth())
        self.Container.setSizePolicy(sizePolicy)
        self.Container.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.Container.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.Container.setObjectName("Container")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Container)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.LabelTitle = QtWidgets.QLabel(self.Container)
        self.LabelTitle.setObjectName("LabelTitle")
        self.horizontalLayout_2.addWidget(self.LabelTitle)
        spacerItem = QtWidgets.QSpacerItem(441, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.LayoutRate = QtWidgets.QHBoxLayout()
        self.LayoutRate.setObjectName("LayoutRate")
        self.LabelRate = QtWidgets.QLabel(self.Container)
        self.LabelRate.setObjectName("LabelRate")
        self.LayoutRate.addWidget(self.LabelRate)
        self.LabelRateValue = QtWidgets.QLabel(self.Container)
        self.LabelRateValue.setObjectName("LabelRateValue")
        self.LayoutRate.addWidget(self.LabelRateValue)
        self.horizontalLayout_2.addLayout(self.LayoutRate)
        self.ButtonOpen = QtWidgets.QPushButton(self.Container)
        self.ButtonOpen.setObjectName("ButtonOpen")
        self.horizontalLayout_2.addWidget(self.ButtonOpen)
        self.LayoutWidget.addWidget(self.Container)

        self.retranslateUi(WidgetMovie)
        QtCore.QMetaObject.connectSlotsByName(WidgetMovie)

    def retranslateUi(self, WidgetMovie):
        _translate = QtCore.QCoreApplication.translate
        self.LabelTitle.setText(_translate("WidgetMovie", "lb.title"))
        self.LabelRate.setText(_translate("WidgetMovie", "lb.rate"))
        self.LabelRateValue.setText(_translate("WidgetMovie", "lb.rate-value"))
        self.ButtonOpen.setText(_translate("WidgetMovie", "btn.open"))
