#!/bin/env bash

ui_path=./layouts/
lang_path=./resources/lang/src/
source_lang="en_US"
target_langs="en_US ru_RU"

for j in $target_langs; do
    lupdate "$ui_path" \
        -recursive \
        -source-language "$source_lang" \
        -target-language "$j" \
        -ts "$lang_path$j.ts"
done
